reporte_users:
    resource: "@ReporteUsersBundle/Controller/"
    type:     annotation
    prefix:   /

#reporte_paginator:
#    resource: "@ReportePaginatorBundle/Resources/config/routing.yml"
#    prefix:   /

reporte_reporte_servicio:
    resource: "@ReporteReporteServicioBundle/Controller/"
    type:     annotation
    prefix:   /

reporte_menu:
    resource: "@ReporteMenuBundle/Controller/"
    type:     annotation
    prefix:   /

reporte_servicio:
    resource: "@ReporteServicioBundle/Controller/"
    type:     annotation
    prefix:   /

reporte_pc:
    resource: "@ReportePCBundle/Controller/"
    type:     annotation
    prefix:   /

reporte_area:
    resource: "@ReporteAreaBundle/Controller/"
    type:     annotation
    prefix:   /

reporte_marca:
    resource: "@ReporteMarcaBundle/Controller/"
    type:     annotation
    prefix:   /

reporte_custom:
    resource: "@ReporteCustomBundle/Controller/"
    type:     annotation
    prefix:   /
    
reporte_user:
    resource: "@ReporteUserBundle/Controller/"
    type:     annotation
    prefix:   /

#Authentication settings
login:
  path: /user/login
  defaults: { _controller: ReporteUserBundle:Default:loginPage }
login_check:
    path: /login_check
logout:
    path: /logout

  
#FOSUserBundle routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
