services:
  login_listener:
    class: Reporte\UserBundle\Listener\LoginListener
    arguments: ["@security.context", "@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }